# Generated by Django 2.2.dev20180904231842 on 2018-09-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_date', models.DateField()),
                ('underlying', models.CharField(choices=[('GBPUSD', 'GBPUSD'), ('GBPEUR', 'GBPEUR')], default='GBPEUR', max_length=6)),
                ('mid', models.FloatField()),
            ],
        ),
    ]
