# Generated by Django 2.2.dev20180904231842 on 2018-09-05 19:53

import csv
import sys

from django.db import migrations


def manip_date(raw_date):
    dmy = raw_date.split('/')

    return '-'.join([dmy[2], dmy[1], dmy[0]])

def import_fixture(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Currency = apps.get_model('validus', 'Currency')

    with open("validus/fixtures/GBPEUR.csv", 'rt', encoding="utf8") as f:
        reader = csv.reader(f, delimiter=';')

        # Skip the header
        next(reader, None)

        for row in reader:
            raw_valuation_date, underlying, mid = row

            cur = Currency()
            cur.valuation_date = manip_date(raw_valuation_date)
            cur.underlying = underlying
            cur.mid = mid

            cur.save()

    with open("validus/fixtures/GBPUSD.csv", 'rt', encoding="utf8") as f:
        reader = csv.reader(f, delimiter=';')

        # Skip the header
        next(reader, None)

        for row in reader:
            raw_valuation_date, underlying, mid = row

            cur = Currency()
            cur.valuation_date = manip_date(raw_valuation_date)
            cur.underlying = underlying
            cur.mid = mid

            cur.save()


class Migration(migrations.Migration):

    dependencies = [
        ('validus', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_fixture),
    ]
